mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# Empty quotes means that's where the application starts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant_menu.urls'))
]

restaurant_menu/urls.py
from django.urls import path
from . import views 

# This means that when the viewer visits the root or the homepage, the default page will be the index.html file as indicated by the MenuList. 
# views means the file where MenuList is coming from.
# For JHCP hackers, the job application form uses function based views

urlpatterns = [
    path('', views.MenuList.as_view(), name='home'),
    # The as_view is required for class based views, but you don't need it for function based views!
    path('item/<int:pk>/', views.MenuItemDetail.as_view(), name="menu_item")
]

restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User

# The first word will be used by the code in the django project
# The second will be used by the front end on the website
# This will  act as a list of values that the cooks can choose from like a drop down list

MEAL_TYPE = (
    ("starters", "Starters"),
    ("salads", "Salads"),
    ("main_dishes", "Main Dishes"),
    ("desserts", "Desserts")
)

# If the status is 0, the selection will be crossed out.
STATUS = (
    (0, "Unavailable"),
    (1, "Available")
)

# Create your models here.
class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    meal_type = models.CharField(max_length=200, choices=MEAL_TYPE)
    # So the author field will be associated with the User table provided by django up at the top of the file.  
    # If the author is “john” , and he is deleted, then all the meals that he has will be deleted as well. 
    # The CASCADE word means delete everything for that user.
    # Alternatively, you can put PROTECT which prohibits the deletion of a user, thereby protecting the meals associcated with that user as well.
    # Leaving it on CASCADE is better for Data Intergrity though, so I will keep it here.
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS, default=0)
    # In the next two lines below, whenever the cook creates a new item or updates the item, the timestamp will be recorded. 
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.meal

restaurant_menu/views.py
from typing import Any
from django.views import generic
# With this we are asking for the data from the database table
from .models import Item, MEAL_TYPE

# This code is to transer data to the HTML frontend from the python and django backend
# We are using a class based system but you could also use a function based systme as well.

# Now we don't have any data, any rows in that table.
# But when we add data later on in the admin interface
# as a cook, we will add some meals, and so on.
# Then this queryset will get those data.
# You can order them using the order_by method.
# You can order them by one of these fields.
# For example, let's take date_created.
# I'll copy that and put it here as a string
# inside quotes, date_created.
# And if you want to reverse the order,
# you just enter a minus before this, so -date_created.

# We are going to have to create the index.html and the menu_item_detail.html files 


class MenuList(generic.ListView):
    queryset = Item.objects.order_by("-date_created")
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        # So the context is a dictionary.
        # And then from your HTML templates,
        # you can access the keys of that dictionary as variables.
        # context = {"meals": ["Pizza", "Pasta"],
        #            "ingredients": ["things"]}
        # But with jinja, we want to start with an empty dictionary
        # So basically we are getting some actual value, an existing dictionary from the ListView class to get some default values already.

        context = super().get_context_data(**kwargs)
        context["meals"] = MEAL_TYPE # we get MEAL_TYPE from models.py
        return context


class MenuItemDetail(generic.DetailView):
    model = Item
    template_name = "menu_item_detail.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <title>Menu Products</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                    <a class="navbar-brand" href="#"></a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                         <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                         <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'home' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}

<!-- JavaScript Bundle with Popper -->
             <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <!-- by default, Django is programmed to look for the templates directoryinside the app directory itself.-->
    <!-- or you go to the settings of your Djang project, which is under mysite, settings.py, and you scroll down to templates, you have this DIRS here And here, you specify templates as a name. So this is relative path to the directory, which contains the templates relative to the project through directory. So I can access templates folder anywhere in my project because it is now specified in the core project -->
    <h1>Restaurant Menu</h1>
    <!-- using jinja2 syntax, we're gonna write a loop to make the html look nicer -->
    <!-- Item_list now comes from the Item class in models.py.
    So our class is named Item, and when you do item with lowercase letters followed by an underscore, followed by list, this is like a special variable name. -->
    <!-- For the row status part, that refers to STATUS from models.py -->
    <ul class="list-group list-group-flush">
        {% for meal in meals %}
            <!-- The class pt-5 defines padding on top of the meals, the meal names-->
            <h2 class="pt-5">{{ meal.1 }}</h2>
                {% for row in item_list %}
                    {% if row.meal_type == meal.0 %}
                        {% if row.status == 0 %}
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                            <a href="{% url 'menu_item' row.pk %}"><h3><del>{{ row.meal }}</del></h3></a>
                            <span class="badge bg-primary rounded-pill">{{ row.price }}</span>
                        </li>
                        <li class="list-group-item pt-0">    
                            <p>{{ row.description }}</p>
                        </li>
                        {% else %}
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                            <a href="{% url 'menu_item' row.pk %}"><h3>{{ row.meal }}</h3></a>
                            <span class="badge bg-primary rounded-pill">{{ row.price }}</span>
                        </li>
                        <li class="list-group-item pt-0">    
                            <p>{{ row.description }}</p>
                        </li>
                        {% endif %}    
                    {% endif %}    
                {% endfor %}
        {% endfor %}
    <!-- <h3>{{ ingredients }}</h3> -->
    </ul>
</div>
{% endblock content %}

templates/menu_item_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1 class="pt-5">{{ item.meal }}</h1>
        <p>{{ item.description }}</p>
        <p>{{ item.price }}</p>
    </div>
{% endblock content %}

templates/static.html
app/
    static/
        css/
            bootstrap.min.css
        js/
            bootstrap.min.js